# Generated by Django 2.2.12 on 2022-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20220903_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='author name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
